baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Bloggy Blog"
theme="basic"
disableKinds= ["RSS"]
[permalinks]
posts = "posts/:year/:month/:slug"
year = "/posts/:slug/"
month = "/posts/:slug"
[taxonomies]
year = "year"
month = "month"
tag = "tags"
category = "categories"